name: easycode
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter

  provider: ^2.0.0-dev
  video_player: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/videos/lecture.mp4
    - assets/Images/GorillaWhile.jpg
    - assets/Images/banana.png